apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/learnwithvikasjha/k8-cluster.git
    targetRevision: main
    path: splunk/instance

  destination:
    server: https://kubernetes.default.svc
    namespace: splunk

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true