apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: mysql-lab
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/learnwithvikasjha/k8-cluster.git
    path: mysql-lab
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: mysql-lab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true